
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: (unknown)
  creationTimestamp: null
  name: hetznerbaremetalmachines.cluster-api-provider-hcloud.capihc.com
spec:
  group: cluster-api-provider-hcloud.capihc.com
  names:
    categories:
    - cluster-api
    kind: HetznerBareMetalMachine
    listKind: HetznerBareMetalMachineList
    plural: hetznerbaremetalmachines
    singular: hetznerbaremetalmachine
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Server state
      jsonPath: .status.serverState
      name: State
      type: string
    - description: Machine ready status
      jsonPath: .status.ready
      name: Ready
      type: string
    - description: Hcloud instance ID
      jsonPath: .spec.providerID
      name: InstanceID
      type: string
    - description: Machine object which owns with this BareMetalMachine
      jsonPath: .metadata.ownerReferences[?(@.kind=="Machine")].name
      name: Machine
      type: string
    name: v1alpha3
    schema:
      openAPIV3Schema:
        description: HetznerBareMetalMachine is the Schema for the bareMetalMachine API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: BareMetalMachineSpec defines the desired state of a BareMetalMachine
            properties:
              imagePath:
                type: string
              partition:
                type: string
              providerID:
                description: ProviderID is the unique identifier as specified by the cloud provider.
                type: string
              serverType:
                type: string
              sshTokenRef:
                properties:
                  privateKey:
                    type: string
                  publicKey:
                    type: string
                  sshKeyName:
                    type: string
                  tokenName:
                    type: string
                required:
                - privateKey
                - publicKey
                - sshKeyName
                - tokenName
                type: object
            required:
            - imagePath
            - serverType
            - sshTokenRef
            type: object
          status:
            description: HetznerBareMetalMachineStatus defines the observed state of HetznerBareMetalMachine
            properties:
              cancelled:
                type: boolean
              failureMessage:
                description: "FailureMessage will be set in the event that there is a terminal problem reconciling the Machine and will contain a more verbose string suitable for logging and human consumption. \n This field should not be set for transitive errors that a controller faces that are expected to be fixed automatically over time (like service outages), but instead indicate that something is fundamentally wrong with the Machine's spec or the configuration of the controller, and that manual intervention is required. Examples of terminal errors would be invalid combinations of settings in the spec, values that are unsupported by the controller, or the responsible controller itself being critically misconfigured. \n Any transient errors that occur during the reconciliation of Machines can be added as events to the Machine object and/or logged in the controller's output."
                type: string
              failureReason:
                description: "FailureReason will be set in the event that there is a terminal problem reconciling the Machine and will contain a succinct value suitable for machine interpretation. \n This field should not be set for transitive errors that a controller faces that are expected to be fixed automatically over time (like service outages), but instead indicate that something is fundamentally wrong with the Machine's spec or the configuration of the controller, and that manual intervention is required. Examples of terminal errors would be invalid combinations of settings in the spec, values that are unsupported by the controller, or the responsible controller itself being critically misconfigured. \n Any transient errors that occur during the reconciliation of Machines can be added as events to the Machine object and/or logged in the controller's output."
                type: string
              ipv6:
                type: string
              ready:
                type: boolean
              rescue:
                type: boolean
              reset:
                type: boolean
              server_ip:
                type: string
              server_name:
                type: string
              server_number:
                type: integer
              serverState:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
